% You likely need to change this prefix dir depending on how you installed
% river-cpp. /usr/local is the default global place on MacOSX, but if you
% installed via conda or are on Windows or linux, it might be elsewhere.
%
% In particular, if you installed via conda, this PREFIX_DIR should
% reference your Anaconda directory (e.g. typically somewhere in ~/anaconda3/envs/<your-env-name>).
% You can look for the file river.h as a marker; if PREFIX_DIR was /usr/local, then you
% would find it at /usr/local/include/river/river.h, so you can pattern
% match different dirs from that.
PREFIX_DIR = '/usr/local/';

include_dir = fullfile(PREFIX_DIR, 'include');
include_hiredis_dir = fullfile(PREFIX_DIR, 'include', 'hiredis');
lib_dir = fullfile(PREFIX_DIR, 'lib');

basenames = { ...
    'stream_schema_mex.cpp', ...
'redis_connection_mex.cpp', ...
'stream_reader_mex.cpp', ...
'stream_writer_mex.cpp',  ...
};
    
for i = 1:length(basenames)
    mex(...
        '-R2018a', ...
        strcat('-I', include_dir), ...
        strcat('-I', include_hiredis_dir), ...
        strcat('-I', lib_dir), ...
        '-lriver', ...
        '-lhiredis', ...
        '-lstdc++', ...
        basenames{i}, ...
        '-v');
end
